name: my first terraform code deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - 'releases/**'

  # pull_request:
  #   branches:
  #     -  main
  #     - 'releases/**'

  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5,17 * * 2,4'
    

jobs:
  my_first_terraform_job:
  name: terraform job
  runs-on: self-hosted
    steps:
      - name: 
     
    
  
